src/Entity/User.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 * @ORM\HasLifecycleCallbacks()
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pseudo;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageLien;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\BacManager", mappedBy="user", cascade={"persist", "remove"})
     */
    private $BacManager;

    /**
     * @ORM\Column(type="integer")
     */
    private $CodePostal;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Ville;

    public function __construct()
    {
        $this->BacManager = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getImageLien(): ?string
    {
        return $this->imageLien;
    }

    public function setImageLien(?string $imageLien): self
    {
        $this->imageLien = $imageLien;

        return $this;
    }

    /**
     * @return Collection|BacManager[]
     */
    public function getBacManager(): Collection
    {
        return $this->BacManager;
    }

    public function addBacManager(BacManager $bacManager): self
    {
        if (!$this->BacManager->contains($bacManager)) {
            $this->BacManager[] = $bacManager;
            $bacManager->setUser($this);
        }

        return $this;
    }

    public function removeBacManager(BacManager $bacManager): self
    {
        if ($this->BacManager->contains($bacManager)) {
            $this->BacManager->removeElement($bacManager);
            // set the owning side to null (unless already changed)
            if ($bacManager->getUser() === $this) {
                $bacManager->setUser(null);
            }
        }

        return $this;
    }

    public function getCodePostal(): ?int
    {
        return $this->CodePostal;
    }

    public function setCodePostal(int $CodePostal): self
    {
        $this->CodePostal = $CodePostal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->Ville;
    }

    public function setVille(string $Ville): self
    {
        $this->Ville = $Ville;

        return $this;
    }
    /**
     * @ORM\PrePersist()
     */
    public function prePersist() {
        $bacJaune = new BacManager;
        $bacJaune->setActif(true)->setCouleur("jaune")->setDateDebut(new DateTime());
        $this->addBacManager($bacJaune);

        $bacGris = new BacManager;
        $bacGris->setActif(true)->setCouleur("gris")->setDateDebut(new DateTime());
        $this->addBacManager($bacGris);

        $bacVerre = new BacManager;
        $bacVerre->setActif(true)->setCouleur("vert")->setDateDebut(new DateTime());
        $this->addBacManager($bacVerre);
    }
}

src/Controller/ProfilController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\RegistrationFormType;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ObjectManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoder;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class ProfilController extends AbstractController
{
    /**
     * @Route("/profil", name="profil", methods="GET")
     */
    public function index()
    {
        return $this->render('profil/index.html.twig', [
            'controller_name' => 'ProfilController',
        ]);
    }

    /**
     *  @Route("/supprimer/{id}", name="supprimer_profil")
     */
    public function supprimerProfil($id)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $user = $entityManager->getRepository(User::class)->find($id);
        $entityManager->remove($user);
        $entityManager->flush();
        return $this->redirectToRoute('app_login');
    }

    /**
     * @Route("/modifier/{id}", name="modifier_profil" )
     */
    public function modifierProfil(User $user, Request $request, EntityManagerInterface $manager, UserPasswordEncoderInterface $encoder) {
        
        $user = $this->getUser();
        
        $form = $this->createForm(RegistrationFormType::class, $user);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
        
            $encodedPassword = $encoder->encodePassword($user, $user->getPassword());
            $user->setPassword($encodedPassword);
            $manager->persist($user);
            $manager->flush();
        }
        return $this->render('profil/modifier-profil.html.twig', [
            'form' => $form->createView()
        ]);
    }
}

templates/profil/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profil{% endblock %}

{% block body %}

<div class="container-fluid mt-2">
    <div class="row d-flex justify-content-center">
        <div class="card col-10 mb-4 text-center">
            <div class="card-header">
                <h5 class="card-title">{{app.user.pseudo}}</h5>
                <div>
                    <a href="{{ path('supprimer_profil', {id:app.user.id}) }}" onclick="return confirm('Etes vous sure de vouloir supprimez votre profil?')"><i class="fas fa-trash"></i></a>
                    <a href="{{ path('modifier_profil', {id:app.user.id}) }}"><i class="far fa-address-card"></i></a>
                </div>
            </div>
            <div class="card-body">

                <div class="d-flex flex-row">
                    <img src="{{asset (app.user.imageLien) }}" class="card-img img-fluid img-thumbnail rounded mb-2"
                        alt="Responsive image" style="max-width: 600px;max-height: 600px">
                    <ul class="card-text text-left">
                        <li>Adresse:
                            {{app.user.adresse}}
                        </li>
                        <li>
                            Ville: {{app.user.ville}}
                            {{app.user.codePostal}}
                        </li>
                        <li>Email:
                            {{app.user.email}}
                        </li>
                    </ul>

                </div>
            </div>

        </div>

    </div>
</div>
{% endblock %}

templates/profil/modifier-profil.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier profil{% endblock %}

{% block body %}
<h1 class="register">Modifier profil</h1>

 <div class="container">
    <div class="row">

        <div class="col-lg-6">
            {{form_start(form)}}
            {{form_row(form.email)}}
            {{form_row(form.pseudo)}}
            {{form_row(form.adresse)}}
            {{form_row(form.codePostal)}}
        </div>

        <div class="col-lg-6">
            {{form_row(form.ville)}}
            {{form_row(form.imageLien)}}
            {{form_row(form.password)}}
            {{form_row(form.password)}} 
            <button class="btn btn-info text-secondary "><a href="{{ path('profil') }}">Valider</a></button>
        </div>
        {{form_end(form)}}

    </div>
</div> 
{% endblock %}